classdef Kin2_Constants < handle
    
    properties (SetAccess=private)%,Hidden=true)
        
        % Joints constants
        JointType = struct(...
            'SpineBase'     ,1,...
            'SpineMid'      ,2,...
            'Neck'          ,3,...
            'Head'          ,4,...
            'ShoulderLeft'  ,5,...
            'ElbowLeft'     ,6,...
            'WristLeft'     ,7,...
            'HandLeft'      ,8,...
            'ShoulderRight' ,9,...
            'ElbowRight'    ,10,...
            'WristRight'    ,11,...
            'HandRight'     ,12,...
            'HipLeft'       ,13,...
            'KneeLeft'      ,14,...
            'AnkleLeft'     ,15,...
            'FootLeft'      ,16,...
            'HipRight'      ,17,...
            'KneeRight'     ,18,...
            'AnkleRight'    ,19,...
            'FootRight'     ,20,...
            'SpineShoulder' ,21,...
            'HandTipLeft'   ,22,...
            'ThumbLeft'     ,23,...
            'HandTipRight'  ,24,...
            'ThumbRight'    ,25,...
            'Count'         ,25);
        
        % Hand State constants
        HandState = struct(...
            'Unknown'       ,0,...
            'NotTracked'    ,1,...
            'Open'          ,2,...
            'Closed'        ,3,...
            'Lasso'         ,4);
        
        % Face detection constants
        DetectionResult = {...
            'Unknown'   ,0;...
            'No'        ,1;...
            'Maybe'     ,2;...
            'Yes'       ,3};
        
        % Face properties
        faceProperties = {...
            'Happy',...
            'Engaged',...
            'Wearing Glasses',...
            'Left eye closed',...
            'Right eye closed',...
            'Mouth open',...
            'Mouth moved',...
            'Looking away'};
        
        % Face Animation units
        faceAnimationUnits = {...
            'JawOpen',...
            'LipPucker',...
            'JawSlideRight',...
            'LipStretcherRight',...
            'LipStretcherLeft',...
            'LipCornerPullerLeft',...
            'LipCornerPullerRight',...
            'LipCornerDepressorLeft',...
            'LipCornerDepressorRight',...
            'LeftcheekPuff',...
            'RightcheekPuff',...
            'LefteyeClosed',...
            'RighteyeClosed',...
            'RighteyebrowLowerer',...
            'LefteyebrowLowerer',...
            'LowerlipDepressorLeft',...
            'LowerlipDepressorRight'};
        
        % FrameSourceTypes 
        FrameSourceTypes = {...
            'none'                      ,0;...
            'color'                     ,1;...
            'infrared'                  ,2;...
            'long_exposure_infrared'    ,4;...
            'depth'                     ,8;...
            'body_index'                ,16;...
            'body'                      ,32;...
            'audio'                     ,64;...
            'face'                      ,128;...
            'HDface'                    ,256};
        
    end
    
end